### ISSUE TITLE
可供运行的环境应该已经搭建好了，运行splitImg没报错，但是没出现结果

### ISSUE THREAD

**Issue by cgliu2000** [TDIT-haha/StoneSegmentator#3]
![image](https://github.com/TDIT-haha/StoneSegmentator/assets/132557991/28973ebf-6668-4c3f-94f3-11ac06285845)
问题如下：
1.在本地和远程的路径调整上浪费了很多时间，目前仍感到混乱。对文件夹路径的管理有没有什么优化建议？
2.连接远程后，只需要conda create一个环境，并activate这个环境吗？还有没有其他必要步骤？
3.运行时缺少各种库，只能一个个手动安装吗？有没有便捷方法？
4.splitImg，每次只是运行一张图片吗？对数据集的制作步骤仍不是很理解。
5.假如输入不同分辨率的图像，需要在哪些地方进行调整？

此外，更主要的问题是（1）很难自己解释程序包中各个文件的作用，哪些文件是最主要的部分，哪部分代码是我后续可能需要自己修改的？（2）程序运行的方法和流程上感觉走了很多弯路，目前还是不太懂得运行逻辑。
恳请能远程实操讲解一下。

**Comment by TDIT-haha** [comment]
1.在本地和远程的路径调整上浪费了很多时间，目前仍感到混乱。对文件夹路径的管理有没有什么优化建议？
暂时没有
2.连接远程后，只需要conda create一个环境，并activate这个环境吗？还有没有其他必要步骤？
暂时没有了
3.运行时缺少各种库，只能一个个手动安装吗？有没有便捷方法？
这里我提供了requirements.txt文件，可以参考readme中安装环境
4.splitImg，每次只是运行一张图片吗？对数据集的制作步骤仍不是很理解。
并不是的，这是选择图像的文件夹地址
5.假如输入不同分辨率的图像，需要在哪些地方进行调整？
不需要，因为是自动，你可以重新pull

**Comment by cgliu2000** [comment]
sorry，下午提出的两个问题我都解决了都是刚发完issue就恍然大悟
下次遇到问题我一定多想一会儿哈哈哈
&nbsp;


lcgeng921
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月22日(星期一) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TDIT-haha/StoneSegmentator] 可供运行的环境应该已经搭建好了，运行splitImg没报错，但是没出现结果 (Issue #3)





 
Closed #3 as completed.
