### ISSUE TITLE
运行sh run.sh 报错 No module named 'segment_anything'

### ISSUE THREAD

**Issue by cgliu2000** [TDIT-haha/StoneSegmentator#4]
(segstone) root@autodl-container-d04f44a835-2d5c31f5:~/project/StoneSegmentator/samseg/segment-anything-main# sh run.sh
Traceback (most recent call last):
  File "scripts/amg.py", line 9, in <module>
    from segment_anything import SamAutomaticMaskGenerator, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

**Comment by TDIT-haha** [comment]
由于sam的安装比较特殊，你需要在samseg/segment-anything-main的目录内 执行 
```
pip install -e .
```
