### ISSUE TITLE
关于/datasets/val 里面的数据

### ISSUE THREAD

**Issue by cgliu2000** [TDIT-haha/StoneSegmentator#5]
![image](https://github.com/TDIT-haha/StoneSegmentator/assets/132557991/d95db547-53ba-4000-9efc-3d1c4be68005)
semseg的run.sh文件，输入文件夹为--input /root/project/StoneSegmentator/example/datasets/val/images \，发现生成的val_outputs_02文件夹下仅有A_4542_0->A_4542_99。疑惑为什么只有4542这张图象呢？（/example/images里面我放了100张图片，欲把100张都利用上。）
发现原因是/example/datasets/val里面的确只有4542。
而saveSplit里面是有所有100张图像的分割结果的。
**于是问题来了：**/datasets下的train和val是怎么生成的呢？****
以及，我需要samseg处理100张图像，应该如何操作？

**Comment by TDIT-haha** [comment]
你可以查阅README.md中这段，对数据的划分
```
cd tools/splitSeg
python splitImg.py  #切割数据,需自己修改图像地址和保存地址savepath01
python splitTrainVal.py #对数据划分训练集和测试机
```
