### ISSUE TITLE
labelme会使用了。但是不明白应该把什么格式的文件（json,label,还是mask)放到labelme里面，以及怎么把它们放到本地来使用。麻烦老师解答。

### ISSUE THREAD

**Issue by cgliu2000** [TDIT-haha/StoneSegmentator#7]
![image](https://github.com/TDIT-haha/StoneSegmentator/assets/132557991/be08c6c9-9724-481a-a155-ad97204fa498)

**Comment by cgliu2000** [comment]
老师可以针对我这套问题做一个教学班吗？每周讲两次课，按小时收取课程费用，引导我全盘走通这个项目，空闲时间我会配合着钻研深度学习基础知识。

**Comment by cgliu2000** [comment]
![image](https://github.com/TDIT-haha/StoneSegmentator/assets/132557991/9f0d87b1-d1c8-4ac0-89e0-a1d2a9ceb17b)
想把用于修改标注的图片打包下载下来，可是压缩不成zip

**Comment by OroChippw** [comment]
> 老师可以针对我这套问题做一个教学班吗？每周讲两次课，按小时收取课程费用，引导我全盘走通这个项目，空闲时间我会配合着钻研深度学习基础知识。

你要不你的联系方式发到我这个邮箱 orochippw@163.com 然后我们根据你的情况 来讨论怎么给你定制这个教学？

**Comment by OroChippw** [comment]
> ![image](https://user-images.githubusercontent.com/132557991/240931255-9f0d87b1-d1c8-4ac0-89e0-a1d2a9ceb17b.png) 想把用于修改标注的图片打包下载下来，可是压缩不成zip

服务器上面应该是默认已经包含了zip指令的 不需要你再去adt-get install了 你下面的报错应该是你的指令没使用正确
同时的话 建议linux下使用tar压缩方式 因为zip方式会有一定的损失，使用方式如下
压缩当前目录下文件夹/文件test到test.tar.gz: 
tar -zcvf test.tar.gz test
