### ISSUE TITLE
best.onnx丢失

### ISSUE THREAD

**Issue by cgliu2000** [TDIT-haha/StoneSegmentator#9]
![image](https://github.com/TDIT-haha/StoneSegmentator/assets/132557991/5e4288c6-c0b6-45da-852c-98a7ace9a026)
这应该是训练好的weights吧，但是运行中被我替换掉了。之前版本在哪里找到？

**Comment by OroChippw** [comment]
README.md里面模型指标重新下载并上传

**Comment by cgliu2000** [comment]
![image](https://github.com/TDIT-haha/StoneSegmentator/assets/132557991/7c34f6b8-fa0a-4d91-83f4-25f7d2503d98)
刚想起来，是不是就是这个呢

**Comment by OroChippw** [comment]
是的

**Comment by cgliu2000** [comment]
![image](https://github.com/TDIT-haha/StoneSegmentator/assets/132557991/7c1ac2fc-15e7-428d-a9a0-dbcdb773b171)
last.pt作何用途

**Comment by OroChippw** [comment]
用于恢复训练

**Comment by cgliu2000** [comment]
不明白

**Comment by OroChippw** [comment]
> 不明白

用于模型训练中途中断，然后恢复继续训练，属于一种进阶技巧
（eg：明天就结束售后不再答疑了喔，会将仓库进行关闭并销毁，你保存好代码喔）
